logging:
  file: logs/oath2-sso.log
  level:
    root: info

server:
  port: 8888

spring:
  aop:
    proxy-target-class: true


#Cluster node port configuration
  data:
    elasticsearch:
      cluster-name: elasticsearch_cc
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enabled: true